//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.04 at 11:31:28 PM IST 
//


package com.omni.oesb.xmlBinding.pacs_008_001_03;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:pacs.008.001.03", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InstructionForCreditorAgent1 }
     * 
     */
    public InstructionForCreditorAgent1 createInstructionForCreditorAgent1() {
        return new InstructionForCreditorAgent1();
    }

    /**
     * Create an instance of {@link CreditTransferTransaction2 }
     * 
     */
    public CreditTransferTransaction2 createCreditTransferTransaction2() {
        return new CreditTransferTransaction2();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification8CdtrAgt }
     * 
     */
    public FinancialInstitutionIdentification8CdtrAgt createFinancialInstitutionIdentification8CdtrAgt() {
        return new FinancialInstitutionIdentification8CdtrAgt();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification1 }
     * 
     */
    public GenericAccountIdentification1 createGenericAccountIdentification1() {
        return new GenericAccountIdentification1();
    }

    /**
     * Create an instance of {@link LocalInstrument2Choice }
     * 
     */
    public LocalInstrument2Choice createLocalInstrument2Choice() {
        return new LocalInstrument2Choice();
    }

    /**
     * Create an instance of {@link PaymentTypeInformation21 }
     * 
     */
    public PaymentTypeInformation21 createPaymentTypeInformation21() {
        return new PaymentTypeInformation21();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification2 }
     * 
     */
    public ClearingSystemMemberIdentification2 createClearingSystemMemberIdentification2() {
        return new ClearingSystemMemberIdentification2();
    }

    /**
     * Create an instance of {@link Charges2 }
     * 
     */
    public Charges2 createCharges2() {
        return new Charges2();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAndAmount }
     * 
     */
    public ActiveOrHistoricCurrencyAndAmount createActiveOrHistoricCurrencyAndAmount() {
        return new ActiveOrHistoricCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link CategoryPurpose1Choice }
     * 
     */
    public CategoryPurpose1Choice createCategoryPurpose1Choice() {
        return new CategoryPurpose1Choice();
    }

    /**
     * Create an instance of {@link CashAccountType2Choice }
     * 
     */
    public CashAccountType2Choice createCashAccountType2Choice() {
        return new CashAccountType2Choice();
    }

    /**
     * Create an instance of {@link FIToFICustomerCreditTransferV03 }
     * 
     */
    public FIToFICustomerCreditTransferV03 createFIToFICustomerCreditTransferV03() {
        return new FIToFICustomerCreditTransferV03();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link SettlementInstruction1 }
     * 
     */
    public SettlementInstruction1 createSettlementInstruction1() {
        return new SettlementInstruction1();
    }

    /**
     * Create an instance of {@link CashAccount24 }
     * 
     */
    public CashAccount24 createCashAccount24() {
        return new CashAccount24();
    }

    /**
     * Create an instance of {@link RemittanceInformation7 }
     * 
     */
    public RemittanceInformation7 createRemittanceInformation7() {
        return new RemittanceInformation7();
    }

    /**
     * Create an instance of {@link PostalAddress6 }
     * 
     */
    public PostalAddress6 createPostalAddress6() {
        return new PostalAddress6();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice }
     * 
     */
    public AccountIdentification4Choice createAccountIdentification4Choice() {
        return new AccountIdentification4Choice();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification5DbtrAgt }
     * 
     */
    public BranchAndFinancialInstitutionIdentification5DbtrAgt createBranchAndFinancialInstitutionIdentification5DbtrAgt() {
        return new BranchAndFinancialInstitutionIdentification5DbtrAgt();
    }

    /**
     * Create an instance of {@link GroupHeader49 }
     * 
     */
    public GroupHeader49 createGroupHeader49() {
        return new GroupHeader49();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification8DbtrAgt }
     * 
     */
    public FinancialInstitutionIdentification8DbtrAgt createFinancialInstitutionIdentification8DbtrAgt() {
        return new FinancialInstitutionIdentification8DbtrAgt();
    }

    /**
     * Create an instance of {@link PaymentIdentification3 }
     * 
     */
    public PaymentIdentification3 createPaymentIdentification3() {
        return new PaymentIdentification3();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification8 }
     * 
     */
    public FinancialInstitutionIdentification8 createFinancialInstitutionIdentification8() {
        return new FinancialInstitutionIdentification8();
    }

    /**
     * Create an instance of {@link PartyIdentification43 }
     * 
     */
    public PartyIdentification43 createPartyIdentification43() {
        return new PartyIdentification43();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification5CdtrAgt }
     * 
     */
    public BranchAndFinancialInstitutionIdentification5CdtrAgt createBranchAndFinancialInstitutionIdentification5CdtrAgt() {
        return new BranchAndFinancialInstitutionIdentification5CdtrAgt();
    }

    /**
     * Create an instance of {@link ServiceLevel8Choice }
     * 
     */
    public ServiceLevel8Choice createServiceLevel8Choice() {
        return new ServiceLevel8Choice();
    }

    /**
     * Create an instance of {@link ActiveCurrencyAndAmount }
     * 
     */
    public ActiveCurrencyAndAmount createActiveCurrencyAndAmount() {
        return new ActiveCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification5 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification5 createBranchAndFinancialInstitutionIdentification5() {
        return new BranchAndFinancialInstitutionIdentification5();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:pacs.008.001.03", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
